# Generated by Django 3.0.8 on 2020-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserModel',
            fields=[
                ('appusers_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField()),
                ('cognito_id', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('user_type', models.TextField()),
                ('newsletter', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'appusers',
            },
        ),
    ]
