# Generated by Django 2.2.17 on 2021-01-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20210106_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusermodel',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
