# Generated by Django 3.0.8 on 2020-12-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilesModel',
            fields=[
                ('productfiles_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.TextField()),
                ('file_extension', models.TextField()),
                ('aws_file_url', models.TextField()),
                ('file_size', models.TextField()),
                ('productfile_name', models.TextField()),
                ('store_file_id', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductModel')),
            ],
            options={
                'db_table': 'product_files',
            },
        ),
    ]
