# Generated by Django 3.0.8 on 2021-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCommunityModel',
            fields=[
                ('joincommunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField(null=True)),
                ('lname', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'join_community',
            },
        ),
    ]
