# Generated by Django 3.0.8 on 2020-12-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProductModel',
            fields=[
                ('favoriteproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.AppUserModel')),
            ],
            options={
                'db_table': 'favoriteproduct',
            },
        ),
    ]
