# Generated by Django 3.0.8 on 2021-03-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_productmonthclickcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWtpSizeModel',
            fields=[
                ('productwtpsize_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductModel')),
            ],
            options={
                'db_table': 'product_wt_p_size',
            },
        ),
    ]
