# Generated by Django 3.0.8 on 2021-03-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productmodel_colors'),
        ('productwtpsize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwtpsizemodel',
            name='attribute_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.AttributeValueModel'),
        ),
    ]
