# Generated by Django 3.0.8 on 2021-03-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productwtpsize', '0002_productwtpsizemodel_attribute_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productwtpsizemodel',
            old_name='weight',
            new_name='size_weight',
        ),
    ]
