# Generated by Django 3.0.8 on 2021-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactindicatormodel',
            name='subjectline',
            field=models.TextField(null=True),
        ),
    ]
