# Generated by Django 3.0.8 on 2021-01-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact_indicator', '0002_impactindicatormodel_subjectline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactindicatormodel',
            old_name='impact_indicator_id',
            new_name='impactindicator_id',
        ),
    ]
