# Generated by Django 3.0.8 on 2021-01-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact_indicator', '0003_auto_20210125_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactindicatormodel',
            old_name='impactindicator_id',
            new_name='impact_indicator_id',
        ),
    ]
