# Generated by Django 3.0.8 on 2021-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_indicator', '0004_auto_20210125_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactindicatormodel',
            old_name='subjectline',
            new_name='blog_subject',
        ),
        migrations.AddField(
            model_name='impactindicatormodel',
            name='blog_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impactindicatormodel',
            name='blog_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
