# Generated by Django 3.0.8 on 2021-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_indicator', '0005_auto_20210127_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactindicatormodel',
            name='brands_doing',
        ),
        migrations.AddField(
            model_name='impactindicatormodel',
            name='shop_now_url',
            field=models.TextField(null=True),
        ),
    ]
