# Generated by Django 3.0.8 on 2020-12-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_chain_id', models.IntegerField(null=True)),
                ('product_name', models.TextField()),
                ('short_description', models.TextField()),
                ('size', models.TextField(blank=True, null=True)),
                ('colors', models.TextField(null=True)),
                ('type_of_fashion_product', models.TextField(null=True)),
                ('product_accessories', models.TextField(null=True)),
                ('product_weight', models.TextField()),
                ('yearly_amount_of_items_procured', models.TextField()),
                ('average_lifetime_of_your_product', models.TextField(blank=True, null=True)),
                ('end_of_life_biodegradable', models.BooleanField(default=False)),
                ('end_of_life_recyclable', models.BooleanField(default=False)),
                ('end_of_life_product_as_a_service', models.BooleanField(default=False)),
                ('end_of_life_repair_service_brand', models.BooleanField(default=False)),
                ('end_of_life_others', models.TextField()),
                ('link_to_brand', models.TextField(null=True)),
                ('gender', models.TextField()),
                ('product_type', models.TextField()),
                ('transparency_score', models.TextField()),
                ('kg_co2_eq', models.TextField()),
                ('km_travelled', models.TextField()),
                ('water_use_liters', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('shopify_product_id', models.TextField()),
                ('platform', models.TextField(default='TCL')),
                ('price', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('product_link', models.TextField(null=True)),
                ('co2_impact', models.TextField(null=True)),
                ('biobased_material', models.BooleanField(default=False)),
                ('refurbished_material', models.BooleanField(default=False)),
                ('reused_material', models.BooleanField(default=False)),
                ('recycled_material', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('second_life_possible', models.BooleanField(default=False)),
                ('social_impact', models.BooleanField(default=False)),
                ('organic_fiber', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.AppUserModel')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
