# Generated by Django 3.0.8 on 2020-12-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='showon_landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
