# Generated by Django 3.0.8 on 2021-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210119_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='social_impact',
            field=models.TextField(null=True),
        ),
    ]
