# Generated by Django 3.0.8 on 2021-02-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210125_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_type',
        ),
    ]
