# Generated by Django 3.0.8 on 2021-03-11 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attributevaluemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMonthClickCount',
            fields=[
                ('product_month_click_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductModel')),
            ],
            options={
                'db_table': 'product_month_click',
            },
        ),
    ]
