# Generated by Django 3.0.8 on 2021-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productmonthclickcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.TextField(null=True),
        ),
    ]
