# Generated by Django 3.0.8 on 2021-03-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productmodel_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='co2_impact',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='kg_co2_eq',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='km_travelled',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='water_use_liters',
        ),
    ]
