# Generated by Django 3.0.8 on 2021-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210330_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='detail_description',
            field=models.TextField(null=True),
        ),
    ]
