# Generated by Django 3.0.8 on 2021-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210503_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmonthclickcount',
            name='ip_address',
            field=models.CharField(default='0:0:0:0', max_length=20),
        ),
    ]
