# Generated by Django 3.0.8 on 2021-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productmonthclickcount_ip_address'),
        ('product', '0013_auto_20210511_1658'),
    ]

    operations = [
    ]
