# Generated by Django 3.0.8 on 2021-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_merge_20210512_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='kgco2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='kmtravel',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='liter',
            field=models.FloatField(null=True),
        ),
    ]
